function createfigure1(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6, YMatrix7, YMatrix8, YMatrix9)
%CREATEFIGURE2(X1, YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4, YMATRIX5, YMATRIX6, YMATRIX7, YMATRIX8, YMATRIX9)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data
%  YMATRIX5:  matrix of y data
%  YMATRIX6:  matrix of y data
%  YMATRIX7:  matrix of y data
%  YMATRIX8:  matrix of y data
%  YMATRIX9:  matrix of y data

%  Auto-generated by MATLAB on 06-Apr-2018 16:35:46

% Create figure
figure1 = figure(2);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.738261385199241 0.213405797101449 0.157741935483871]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','Command','Color',[1 0 0]);
set(plot1(2),'DisplayName','With Differential Flatness','Color',[0 0 1]);
set(plot1(3),'DisplayName','PID Only','LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('Pn','fontsize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.130038932167366 0.914890663988086 0.109209345760157 0.0499500508526284],...
    'fontsize',12);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.410797101449276 0.709264705882353 0.213405797101449 0.215735294117647]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'LineWidth',2);
set(plot2(1),'Color',[1 0 0]);
set(plot2(2),'Color',[0 0 1]);
set(plot2(3),'LineStyle','--','Color',[0 0 0]);

% Create title
title('UAV States Over Time','fontsize',16);

% Create ylabel
ylabel('Pe','fontsize',12);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.691594202898551 0.709264705882353 0.213405797101449 0.215735294117647]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',axes3,'LineWidth',2);
set(plot3(1),'Color',[1 0 0]);
set(plot3(2),'Color',[0 0 1]);
set(plot3(3),'LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('Pd','fontsize',12);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.13 0.409632352941176 0.213405797101449 0.215735294117647]);
hold(axes4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',axes4,'LineWidth',2);
set(plot4(1),'Color',[1 0 0]);
set(plot4(2),'Color',[0 0 1]);
set(plot4(3),'LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('u','fontsize',12);

% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.410797101449276 0.409632352941176 0.213405797101449 0.215735294117647]);
hold(axes5,'on');

% Create multiple lines using matrix input to plot
plot5 = plot(X1,YMatrix5,'Parent',axes5,'LineWidth',2);
set(plot5(1),'Color',[1 0 0]);
set(plot5(2),'Color',[0 0 1]);
set(plot5(3),'LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('v','fontsize',12);

% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.691594202898551 0.409632352941176 0.213405797101449 0.215735294117647]);
hold(axes6,'on');

% Create multiple lines using matrix input to plot
plot6 = plot(X1,YMatrix6,'Parent',axes6,'LineWidth',2);
set(plot6(1),'Color',[1 0 0]);
set(plot6(2),'Color',[0 0 1]);
set(plot6(3),'LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('w','fontsize',12);

% Create axes
axes7 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.213405797101449 0.215735294117647]);
hold(axes7,'on');

% Create multiple lines using matrix input to plot
plot7 = plot(X1,YMatrix7,'Parent',axes7,'LineWidth',2);
set(plot7(1),'Color',[1 0 0]);
set(plot7(2),'Color',[0 0 1]);
set(plot7(3),'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('t','fontsize',12);

% Create ylabel
ylabel('Roll','fontsize',12);

% Create axes
axes8 = axes('Parent',figure1,...
    'Position',[0.410797101449276 0.11 0.213405797101449 0.215735294117647]);
hold(axes8,'on');

% Create multiple lines using matrix input to plot
plot8 = plot(X1,YMatrix8,'Parent',axes8,'LineWidth',2);
set(plot8(1),'Color',[1 0 0]);
set(plot8(2),'Color',[0 0 1]);
set(plot8(3),'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('t','fontsize',12);

% Create ylabel
ylabel('Pitch','fontsize',12);

% Create axes
axes9 = axes('Parent',figure1,...
    'Position',[0.691594202898551 0.11 0.213405797101449 0.215735294117647]);
hold(axes9,'on');

% Create multiple lines using matrix input to plot
plot9 = plot(X1,YMatrix9,'Parent',axes9,'LineWidth',2);
set(plot9(1),'Color',[1 0 0]);
set(plot9(2),'Color',[0 0 1]);
set(plot9(3),'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('t','fontsize',12);

% Create ylabel
ylabel('r','fontsize',12);

